# Generated by Django 4.0.6 on 2022-07-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_permission',
            field=models.CharField(choices=[('superuser', 'Yönetici'), ('user', 'Kullanıcı')], default='user', help_text='Kullanıcının sitedeki erişim sınırını belirler.', max_length=20, verbose_name='Kullanıcı Yetki'),
        ),
    ]
